import { render, screen, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { describe, expect, it, vi } from "vitest";

import { WorkspaceOnboarding } from "./WorkspaceOnboarding";

/**
 * The two ways into a workspace, before anyone has one.
 *
 * Creating asks for a name and a password (twice); joining asks for a code and
 * a password. Neither lets anyone choose a code — the server makes it.
 */

function setup(props: Partial<React.ComponentProps<typeof WorkspaceOnboarding>> = {}) {
  const onCreate = vi.fn();
  const onJoin = vi.fn();
  const user = userEvent.setup();
  render(
    <WorkspaceOnboarding
      displayName="Sam"
      busy={false}
      error={null}
      onCreate={onCreate}
      onJoin={onJoin}
      onSignOut={() => {}}
      {...props}
    />,
  );
  const create = screen.getByRole("form", { name: /create a workspace/i });
  const join = screen.getByRole("form", { name: /join a workspace/i });
  return { user, onCreate, onJoin, create: within(create), join: within(join) };
}

describe("creating a workspace", () => {
  it("asks for a name, a password and its confirmation — and for no code", () => {
    const { create } = setup();

    expect(create.getByLabelText("Workspace name")).toBeInTheDocument();
    expect(create.getByLabelText("Workspace password")).toHaveAttribute("type", "password");
    expect(create.getByLabelText("Confirm workspace password")).toHaveAttribute(
      "type",
      "password",
    );
    // The code is generated by the server; there is nothing to type it into.
    expect(create.queryByLabelText(/workspace code/i)).toBeNull();
  });

  it("sends the name and the password twice, once they match", async () => {
    const { user, create, onCreate } = setup();

    await user.type(create.getByLabelText("Workspace name"), "Acme Logistics");
    await user.type(create.getByLabelText("Workspace password"), "team-passphrase");
    await user.type(create.getByLabelText("Confirm workspace password"), "team-passphrase");
    await user.click(create.getByRole("button", { name: /create workspace/i }));

    expect(onCreate).toHaveBeenCalledWith({
      name: "Acme Logistics",
      workspacePassword: "team-passphrase",
      confirmWorkspacePassword: "team-passphrase",
    });
  });

  it("refuses a password that does not match its confirmation, without asking the server", async () => {
    const { user, create, onCreate } = setup();

    await user.type(create.getByLabelText("Workspace name"), "Acme Logistics");
    await user.type(create.getByLabelText("Workspace password"), "team-passphrase");
    await user.type(create.getByLabelText("Confirm workspace password"), "team-passphrasE");
    await user.click(create.getByRole("button", { name: /create workspace/i }));

    expect(create.getByText("The workspace passwords do not match.")).toBeInTheDocument();
    expect(onCreate).not.toHaveBeenCalled();
  });

  it("refuses a password shorter than the server's minimum", async () => {
    const { user, create, onCreate } = setup();

    await user.type(create.getByLabelText("Workspace name"), "Acme Logistics");
    await user.type(create.getByLabelText("Workspace password"), "short");
    await user.type(create.getByLabelText("Confirm workspace password"), "short");
    await user.click(create.getByRole("button", { name: /create workspace/i }));

    expect(
      create.getByText("Workspace password must be at least 8 characters."),
    ).toBeInTheDocument();
    expect(onCreate).not.toHaveBeenCalled();
  });

  it("shows a refusal from the server under the creation form only", async () => {
    const { user, create, join, onCreate } = setup({ error: "Could not do that." });
    await user.type(create.getByLabelText("Workspace name"), "Acme Logistics");
    await user.type(create.getByLabelText("Workspace password"), "team-passphrase");
    await user.type(create.getByLabelText("Confirm workspace password"), "team-passphrase");
    await user.click(create.getByRole("button", { name: /create workspace/i }));

    expect(onCreate).toHaveBeenCalled();
    // The panel places the error by which form was submitted.
    expect(create.getByRole("alert")).toHaveTextContent("Could not do that.");
    expect(join.queryByRole("alert")).toBeNull();
  });
});

describe("joining a workspace", () => {
  it("asks for a code and a password", () => {
    const { join } = setup();

    expect(join.getByLabelText("Workspace code")).toBeInTheDocument();
    expect(join.getByLabelText("Workspace password")).toHaveAttribute("type", "password");
  });

  it("sends the code and the password together", async () => {
    const { user, join, onJoin } = setup();

    await user.type(join.getByLabelText("Workspace code"), "K7Q2M9XPAB");
    await user.type(join.getByLabelText("Workspace password"), "team-passphrase");
    await user.click(join.getByRole("button", { name: /join workspace/i }));

    expect(onJoin).toHaveBeenCalledWith({
      workspaceCode: "K7Q2M9XPAB",
      workspacePassword: "team-passphrase",
    });
  });

  it("does not offer to join with a code alone", async () => {
    const { user, join, onJoin } = setup();

    await user.type(join.getByLabelText("Workspace code"), "K7Q2M9XPAB");
    await user.click(join.getByRole("button", { name: /join workspace/i }));

    // The password field is required, so the form never submits.
    expect(onJoin).not.toHaveBeenCalled();
  });

  it("shows the server's refusal under the join form", async () => {
    const view = setup({ error: "That workspace code and password don't match." });
    await view.user.type(view.join.getByLabelText("Workspace code"), "ZZZZZZZZZZ");
    await view.user.type(view.join.getByLabelText("Workspace password"), "not-the-password");
    await view.user.click(view.join.getByRole("button", { name: /join workspace/i }));

    expect(view.onJoin).toHaveBeenCalled();
    expect(view.join.getByRole("alert")).toHaveTextContent(
      "That workspace code and password don't match.",
    );
    expect(view.create.queryByRole("alert")).toBeNull();
  });
});
