"use client";

import { useState } from "react";

import { Button } from "./ui/Button";
import { Callout } from "./ui/Callout";
import { TextField } from "./ui/Field";

import type { CreateWorkspaceInput, JoinWorkspaceInput } from "@/lib/auth-client";

import styles from "./WorkspaceOnboarding.module.css";

/**
 * What a signed-in user sees when they belong to no workspace.
 *
 * This is not an error state and must not read like one. A new account is at
 * the *beginning*: the backend reports `needs_workspace`, not a failure, and
 * the copy here explains what a workspace is before asking for anything.
 *
 * There are two ways in, and they are the only two: create a workspace (a name,
 * and a password people will join it with), or join one somebody else made (its
 * code and that password). The code is generated by the server and shown to the
 * owner once the workspace exists; nothing here lets anyone choose one.
 */
const HOLDS: string[] = [
  "The accounts, orders and tickets the assistant may look up.",
  "The policies, SOPs and signed customer agreements it answers from.",
  "The people you work with, and what each of them is allowed to do.",
  "Every action it prepares, and the audit trail of who confirmed what.",
];

/**
 * The shortest password the backend will store — the same rule as an account
 * password (`MIN_PASSWORD_LENGTH` in `app/backend/auth/passwords.py`, which is
 * the authority). A copy so the form can say so before a round trip.
 */
const MIN_PASSWORD_LENGTH = 8;

export function WorkspaceOnboarding({
  displayName,
  busy,
  error,
  onCreate,
  onJoin,
  onSignOut,
}: {
  displayName: string;
  busy: boolean;
  error: string | null;
  onCreate(input: CreateWorkspaceInput): void;
  onJoin(input: JoinWorkspaceInput): void;
  onSignOut(): void;
}) {
  const [name, setName] = useState("");
  const [password, setPassword] = useState("");
  const [confirm, setConfirm] = useState("");
  const [passwordError, setPasswordError] = useState<string | null>(null);
  const [confirmError, setConfirmError] = useState<string | null>(null);
  const [submitted, setSubmitted] = useState<"create" | "join" | null>(null);

  const [code, setCode] = useState("");
  const [joinPassword, setJoinPassword] = useState("");

  function create(event: React.FormEvent) {
    event.preventDefault();
    const tooShort =
      password.length < MIN_PASSWORD_LENGTH
        ? `Workspace password must be at least ${MIN_PASSWORD_LENGTH} characters.`
        : null;
    // Compared exactly: trimming or case-folding would let someone "confirm" a
    // password they did not type.
    const mismatched =
      !tooShort && password !== confirm ? "The workspace passwords do not match." : null;
    setPasswordError(tooShort);
    setConfirmError(mismatched);
    if (tooShort || mismatched) return;

    setSubmitted("create");
    onCreate({
      name,
      workspacePassword: password,
      confirmWorkspacePassword: confirm,
    });
  }

  function join(event: React.FormEvent) {
    event.preventDefault();
    setSubmitted("join");
    onJoin({ workspaceCode: code, workspacePassword: joinPassword });
  }

  // A server refusal belongs under the form that caused it.
  const createError = submitted === "create" ? error : null;
  const joinError = submitted === "join" ? error : null;

  return (
    <div className={styles.panel}>
      <p className={styles.eyebrow}>Welcome, {displayName}</p>
      <h1 className={styles.title}>Create your first workspace</h1>

      <p className={styles.lede}>
        A workspace is where your operation lives in ASTRION. It holds:
      </p>

      <ul className={styles.holds}>
        {HOLDS.map((item) => (
          <li key={item} className={styles.holdsItem}>
            <span className={styles.holdsMark} aria-hidden="true" />
            <span>{item}</span>
          </li>
        ))}
      </ul>

      <p className={styles.lede}>
        Workspaces are how ASTRION keeps one operation&apos;s data separate
        from another&apos;s. The separation is enforced on the server, not in
        this browser: the assistant can only ever see what your workspace owns.
      </p>

      <form className={styles.form} aria-label="Create a workspace" onSubmit={create}>
        <TextField
          label="Workspace name"
          value={name}
          onChange={(event) => setName(event.target.value)}
          placeholder="Acme Logistics"
          hint="Usually your company or team name. You can change it later."
          minLength={2}
          maxLength={120}
          required
          autoFocus
        />

        <TextField
          label="Workspace password"
          type="password"
          value={password}
          onChange={(event) => {
            setPassword(event.target.value);
            setPasswordError(null);
            setConfirmError(null);
          }}
          autoComplete="new-password"
          hint={`What people will need, with the workspace code, to join. At least ${MIN_PASSWORD_LENGTH} characters. It is stored only as a hash and cannot be shown again.`}
          error={passwordError}
          required
        />

        <TextField
          label="Confirm workspace password"
          type="password"
          value={confirm}
          onChange={(event) => {
            setConfirm(event.target.value);
            setConfirmError(null);
          }}
          autoComplete="new-password"
          error={confirmError}
          required
        />

        {createError ? (
          <Callout tone="fail" role="alert" title="Could not create the workspace">
            {createError}
          </Callout>
        ) : null}

        <Button type="submit" variant="primary" block disabled={busy}>
          {busy && submitted === "create" ? "Creating…" : "Create workspace"}
        </Button>
      </form>

      <p className={styles.footnote}>
        A new workspace starts empty. Records reach it when an operator attaches
        them on the server — nothing is invented here, so the assistant will say
        it cannot find an order rather than answer about one you do not have.
      </p>

      <section className={styles.join} aria-labelledby="join-workspace-title">
        <h2 id="join-workspace-title" className={styles.joinTitle}>
          Join a workspace
        </h2>
        <p className={styles.lede}>
          Been given a workspace code and password? Enter both. The code alone
          does not open anything.
        </p>

        <form className={styles.form} aria-label="Join a workspace" onSubmit={join}>
          <TextField
            label="Workspace code"
            value={code}
            onChange={(event) => setCode(event.target.value)}
            autoComplete="off"
            autoCapitalize="characters"
            spellCheck={false}
            maxLength={64}
            required
          />
          <TextField
            label="Workspace password"
            type="password"
            value={joinPassword}
            onChange={(event) => setJoinPassword(event.target.value)}
            autoComplete="off"
            required
          />

          {joinError ? (
            <Callout tone="fail" role="alert" title="Could not join the workspace">
              {joinError}
            </Callout>
          ) : null}

          <Button type="submit" variant="secondary" block disabled={busy}>
            {busy && submitted === "join" ? "Joining…" : "Join workspace"}
          </Button>
        </form>
      </section>

      <div className={styles.actions}>
        <Button variant="ghost" size="sm" onClick={onSignOut}>
          Sign out
        </Button>
      </div>
    </div>
  );
}
