-- 0001 baseline: the schema as it stood when the database moved to PostgreSQL.
--
-- Derived from the SQLite schema (app/backend/services/database.py and
-- app/backend/auth/schema.py) and kept in step with it by
-- tests/test_db_schema_parity.py. Nothing here is new behaviour.
--
-- Differences from SQLite, all mechanical:
--   * AUTOINCREMENT  -> GENERATED BY DEFAULT AS IDENTITY
--   * STRICT         -> dropped (PostgreSQL columns are always typed)
--   * REAL           -> DOUBLE PRECISION
--   * TEXT columns   -> COLLATE "C", so ordering and equality are bytewise as
--                       they were, whatever the server's locale
-- Timestamps stay ISO-8601 TEXT and flags stay 0/1 INTEGER on purpose: the
-- queries compare and count them as such, and changing representation is a
-- separate decision from changing engine.

CREATE TABLE IF NOT EXISTS dataset_metadata (
        id INTEGER PRIMARY KEY CHECK (id = 1),
        dataset_snapshot_raw TEXT COLLATE "C" NOT NULL,
        dataset_snapshot_at TEXT COLLATE "C" NOT NULL,
        dataset_timezone TEXT COLLATE "C" NOT NULL,
        currency TEXT COLLATE "C",
        notes TEXT COLLATE "C",
        important_note TEXT COLLATE "C",
        source_workbook_filename TEXT COLLATE "C" NOT NULL,
        source_workbook_sha256 TEXT COLLATE "C" NOT NULL,
        source_sheet_names TEXT COLLATE "C" NOT NULL,
        ingested_at_utc TEXT COLLATE "C" NOT NULL,
        ingestion_script_version TEXT COLLATE "C" NOT NULL
    );

CREATE TABLE IF NOT EXISTS ingestion_runs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        started_at_utc TEXT COLLATE "C" NOT NULL,
        finished_at_utc TEXT COLLATE "C",
        source_workbook_path TEXT COLLATE "C" NOT NULL,
        source_workbook_sha256 TEXT COLLATE "C" NOT NULL,
        ingestion_script_version TEXT COLLATE "C" NOT NULL,
        status TEXT COLLATE "C" NOT NULL DEFAULT 'running'
    );

CREATE TABLE IF NOT EXISTS accounts (
        account_id TEXT COLLATE "C" PRIMARY KEY,
        account_name TEXT COLLATE "C",
        plan TEXT COLLATE "C",
        status TEXT COLLATE "C",
        csm TEXT COLLATE "C",
        contract_file TEXT COLLATE "C",
        premium_support INTEGER,
        notes TEXT COLLATE "C"
    );

CREATE TABLE IF NOT EXISTS orders (
        order_id TEXT COLLATE "C" PRIMARY KEY,
        account_id TEXT COLLATE "C" NOT NULL REFERENCES accounts (account_id),
        carrier TEXT COLLATE "C",
        status TEXT COLLATE "C",
        booked_at TEXT COLLATE "C",
        pickup_window_start TEXT COLLATE "C",
        pickup_window_end TEXT COLLATE "C",
        pickup_actual_at TEXT COLLATE "C",
        shipment_fee_inr DOUBLE PRECISION,
        carrier_fault INTEGER,
        customer_fault INTEGER,
        cancellation_requested_at TEXT COLLATE "C",
        notes TEXT COLLATE "C"
    );

CREATE TABLE IF NOT EXISTS tickets (
        ticket_id TEXT COLLATE "C" PRIMARY KEY,
        account_id TEXT COLLATE "C" NOT NULL REFERENCES accounts (account_id),
        created_at TEXT COLLATE "C",
        status TEXT COLLATE "C",
        subject TEXT COLLATE "C",
        description TEXT COLLATE "C",
        channel TEXT COLLATE "C",
        assigned_to TEXT COLLATE "C",
        last_customer_message_at TEXT COLLATE "C",
        historical_resolution TEXT COLLATE "C"
    );

CREATE TABLE IF NOT EXISTS source_provenance (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ingestion_run_id INTEGER NOT NULL REFERENCES ingestion_runs (id),
        target_table TEXT COLLATE "C" NOT NULL,
        target_id TEXT COLLATE "C" NOT NULL,
        source_file TEXT COLLATE "C" NOT NULL,
        source_sheet TEXT COLLATE "C" NOT NULL,
        source_row_number INTEGER NOT NULL,
        raw_row_json TEXT COLLATE "C" NOT NULL,
        UNIQUE (target_table, target_id)
    );

CREATE TABLE IF NOT EXISTS document_ingestion_runs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        started_at_utc TEXT COLLATE "C" NOT NULL,
        finished_at_utc TEXT COLLATE "C",
        source_dir TEXT COLLATE "C" NOT NULL,
        document_count INTEGER,
        chunk_count INTEGER,
        ingestion_script_version TEXT COLLATE "C" NOT NULL,
        status TEXT COLLATE "C" NOT NULL DEFAULT 'running'
    );

CREATE TABLE IF NOT EXISTS documents (
        document_id TEXT COLLATE "C" PRIMARY KEY,
        source_file TEXT COLLATE "C" NOT NULL UNIQUE,
        source_sha256 TEXT COLLATE "C" NOT NULL,
        title TEXT COLLATE "C" NOT NULL,
        document_type TEXT COLLATE "C" NOT NULL,
        status TEXT COLLATE "C" NOT NULL,
        status_raw TEXT COLLATE "C" NOT NULL,
        is_current INTEGER NOT NULL,
        is_deprecated INTEGER NOT NULL,
        is_authoritative INTEGER NOT NULL,
        authority_tier INTEGER NOT NULL,
        account_id TEXT COLLATE "C",
        customer_name TEXT COLLATE "C",
        plan TEXT COLLATE "C",
        effective_date_raw TEXT COLLATE "C",
        effective_date TEXT COLLATE "C",
        updated_date_raw TEXT COLLATE "C",
        updated_date TEXT COLLATE "C",
        term_raw TEXT COLLATE "C",
        term_start TEXT COLLATE "C",
        term_end TEXT COLLATE "C",
        supersedes TEXT COLLATE "C",
        superseded_by TEXT COLLATE "C",
        page_count INTEGER NOT NULL,
        ingestion_run_id INTEGER NOT NULL
            REFERENCES document_ingestion_runs (id)
    );

CREATE TABLE IF NOT EXISTS document_chunks (
        chunk_id TEXT COLLATE "C" PRIMARY KEY,
        document_id TEXT COLLATE "C" NOT NULL REFERENCES documents (document_id),
        chunk_ordinal INTEGER NOT NULL,
        page_number INTEGER NOT NULL,
        section_number TEXT COLLATE "C",
        section_title TEXT COLLATE "C",
        subsection_title TEXT COLLATE "C",
        section_path TEXT COLLATE "C",
        topic TEXT COLLATE "C" NOT NULL,
        text TEXT COLLATE "C" NOT NULL,
        char_count INTEGER NOT NULL,
        word_count INTEGER NOT NULL,
        page_char_start INTEGER NOT NULL,
        page_char_end INTEGER NOT NULL,
        UNIQUE (document_id, chunk_ordinal)
    );

CREATE TABLE IF NOT EXISTS agent_actions (
        action_id TEXT COLLATE "C" PRIMARY KEY,
        action_type TEXT COLLATE "C" NOT NULL,
        status TEXT COLLATE "C" NOT NULL,
        account_id TEXT COLLATE "C",
        target_type TEXT COLLATE "C" NOT NULL,
        target_id TEXT COLLATE "C" NOT NULL,
        parameters_json TEXT COLLATE "C" NOT NULL,
        preview TEXT COLLATE "C" NOT NULL,
        reason TEXT COLLATE "C",
        evidence_chunk_ids_json TEXT COLLATE "C" NOT NULL,
        requested_by TEXT COLLATE "C" NOT NULL,
        requested_by_role TEXT COLLATE "C" NOT NULL,
        -- The conversation the proposal was produced in (Phase 5). Nullable:
        -- a Phase 4 caller with no session still prepares actions normally.
        -- Bound at preparation and re-checked at confirmation, so a proposal
        -- cannot be confirmed from a different conversation.
        session_id TEXT COLLATE "C",
        confirmed_by TEXT COLLATE "C",
        prepared_at_utc TEXT COLLATE "C" NOT NULL,
        expires_at_utc TEXT COLLATE "C" NOT NULL,
        confirmed_at_utc TEXT COLLATE "C",
        executed_at_utc TEXT COLLATE "C",
        rejected_at_utc TEXT COLLATE "C",
        result_json TEXT COLLATE "C",
        failure_reason TEXT COLLATE "C"
    );

CREATE TABLE IF NOT EXISTS ticket_escalations (
        escalation_id TEXT COLLATE "C" PRIMARY KEY,
        action_id TEXT COLLATE "C" NOT NULL REFERENCES agent_actions (action_id),
        ticket_id TEXT COLLATE "C" NOT NULL,
        account_id TEXT COLLATE "C",
        severity TEXT COLLATE "C",
        reason TEXT COLLATE "C" NOT NULL,
        created_by TEXT COLLATE "C" NOT NULL,
        created_at_utc TEXT COLLATE "C" NOT NULL
    );

CREATE TABLE IF NOT EXISTS service_credits (
        credit_id TEXT COLLATE "C" PRIMARY KEY,
        action_id TEXT COLLATE "C" NOT NULL REFERENCES agent_actions (action_id),
        order_id TEXT COLLATE "C" NOT NULL,
        account_id TEXT COLLATE "C",
        -- Money is stored as the policy engine's own decimal string, never a
        -- float. `policies/` works in Decimal precisely so a credit is not
        -- subject to binary rounding, and persisting it as DOUBLE PRECISION here would
        -- reintroduce exactly that.
        amount TEXT COLLATE "C" NOT NULL,
        currency TEXT COLLATE "C" NOT NULL,
        -- Whether the SOP's manager threshold applied, and who signed it off.
        -- Kept beside the credit so the approval is reconstructable from the
        -- row itself rather than only from the audit log.
        required_manager_approval INTEGER NOT NULL DEFAULT 0,
        approved_by TEXT COLLATE "C" NOT NULL,
        created_at_utc TEXT COLLATE "C" NOT NULL
    );

CREATE TABLE IF NOT EXISTS ticket_notes (
        note_id TEXT COLLATE "C" PRIMARY KEY,
        action_id TEXT COLLATE "C" NOT NULL REFERENCES agent_actions (action_id),
        ticket_id TEXT COLLATE "C" NOT NULL,
        account_id TEXT COLLATE "C",
        note TEXT COLLATE "C" NOT NULL,
        created_by TEXT COLLATE "C" NOT NULL,
        created_at_utc TEXT COLLATE "C" NOT NULL
    );

CREATE INDEX IF NOT EXISTS idx_orders_account_id ON orders (account_id);

CREATE INDEX IF NOT EXISTS idx_tickets_account_id ON tickets (account_id);

CREATE INDEX IF NOT EXISTS idx_documents_account_id ON documents (account_id);

CREATE INDEX IF NOT EXISTS idx_chunks_document_id ON document_chunks (document_id);

CREATE INDEX IF NOT EXISTS idx_chunks_topic ON document_chunks (topic);

CREATE INDEX IF NOT EXISTS idx_actions_status ON agent_actions (status);

CREATE INDEX IF NOT EXISTS idx_actions_target ON agent_actions (target_type, target_id);

CREATE TABLE IF NOT EXISTS users (
        user_id TEXT COLLATE "C" PRIMARY KEY,
        -- Stored lower-cased and stripped. UNIQUE here is what makes
        -- registration safe against a read-then-write race that would
        -- otherwise create two accounts for one address.
        email TEXT COLLATE "C" NOT NULL UNIQUE,
        email_verified INTEGER NOT NULL DEFAULT 0,
        display_name TEXT COLLATE "C" NOT NULL,
        -- scrypt hash, self-describing. See app/backend/auth/passwords.py
        password_hash TEXT COLLATE "C" NOT NULL,
        password_updated_at_utc TEXT COLLATE "C" NOT NULL,
        -- Base32 TOTP secret. NULL until enrolment; mfa_enabled stays 0 until
        -- a first code is verified, so a half-finished enrolment cannot lock a
        -- user out of their own account.
        mfa_secret TEXT COLLATE "C",
        mfa_enabled INTEGER NOT NULL DEFAULT 0,
        -- The last TOTP time-step spent, so a code cannot be replayed inside
        -- its own acceptance window.
        mfa_last_step INTEGER,
        status TEXT COLLATE "C" NOT NULL DEFAULT 'active',
        created_at_utc TEXT COLLATE "C" NOT NULL,
        last_login_at_utc TEXT COLLATE "C"
    );

CREATE TABLE IF NOT EXISTS organizations (
        org_id TEXT COLLATE "C" PRIMARY KEY,
        name TEXT COLLATE "C" NOT NULL,
        slug TEXT COLLATE "C" NOT NULL UNIQUE,
        status TEXT COLLATE "C" NOT NULL DEFAULT 'active',
        created_at_utc TEXT COLLATE "C" NOT NULL
    );

CREATE TABLE IF NOT EXISTS memberships (
        membership_id TEXT COLLATE "C" PRIMARY KEY,
        org_id TEXT COLLATE "C" NOT NULL REFERENCES organizations (org_id),
        user_id TEXT COLLATE "C" NOT NULL REFERENCES users (user_id),
        role TEXT COLLATE "C" NOT NULL,
        status TEXT COLLATE "C" NOT NULL DEFAULT 'active',
        created_at_utc TEXT COLLATE "C" NOT NULL,
        updated_at_utc TEXT COLLATE "C" NOT NULL,
        -- One membership per user per organisation. Without this, a second
        -- INSERT would silently grant a second, possibly higher, role.
        UNIQUE (org_id, user_id)
    );

-- How a workspace is joined: a code the server generated and a password its
    -- owner chose. Its own table rather than columns on `organizations`, so no
    -- `SELECT * FROM organizations` -- and there are several -- can carry the
    -- hash into a response. A workspace with no row here (the seeded demo, one
    -- created by a script) simply cannot be joined by code.
    CREATE TABLE IF NOT EXISTS workspace_access (
        org_id TEXT COLLATE "C" PRIMARY KEY REFERENCES organizations (org_id),
        -- Unique at the database, not only in the generator: two workspaces
        -- with one code would let a password for one open the other.
        workspace_code TEXT COLLATE "C" NOT NULL UNIQUE,
        password_hash TEXT COLLATE "C" NOT NULL,
        owner_user_id TEXT COLLATE "C" NOT NULL REFERENCES users (user_id),
        created_at_utc TEXT COLLATE "C" NOT NULL,
        password_changed_at_utc TEXT COLLATE "C" NOT NULL
    );

CREATE TABLE IF NOT EXISTS organization_accounts (
        org_id TEXT COLLATE "C" NOT NULL REFERENCES organizations (org_id),
        account_id TEXT COLLATE "C" NOT NULL,
        created_at_utc TEXT COLLATE "C" NOT NULL,
        PRIMARY KEY (org_id, account_id)
    );

CREATE TABLE IF NOT EXISTS sessions (
        session_id TEXT COLLATE "C" PRIMARY KEY,
        -- SHA-256 of the cookie value. The cookie itself is never stored, so
        -- a database disclosure yields no usable session.
        token_hash TEXT COLLATE "C" NOT NULL UNIQUE,
        user_id TEXT COLLATE "C" NOT NULL REFERENCES users (user_id),
        -- The organisation this session is acting in. Every tenant-scoped
        -- query derives its scope from this column, never from the request.
        org_id TEXT COLLATE "C" REFERENCES organizations (org_id),
        created_at_utc TEXT COLLATE "C" NOT NULL,
        last_seen_at_utc TEXT COLLATE "C" NOT NULL,
        -- Two independent clocks: a session dies at the absolute deadline
        -- however active it has been, and dies early if left idle.
        absolute_expires_at_utc TEXT COLLATE "C" NOT NULL,
        idle_expires_at_utc TEXT COLLATE "C" NOT NULL,
        revoked_at_utc TEXT COLLATE "C",
        -- 0 between password and second factor. A half-authenticated session
        -- can reach the MFA endpoint and nothing else.
        mfa_satisfied INTEGER NOT NULL DEFAULT 0,
        ip_hash TEXT COLLATE "C",
        user_agent_hash TEXT COLLATE "C"
    );

CREATE TABLE IF NOT EXISTS auth_tokens (
        token_id TEXT COLLATE "C" PRIMARY KEY,
        token_hash TEXT COLLATE "C" NOT NULL UNIQUE,
        purpose TEXT COLLATE "C" NOT NULL,
        user_id TEXT COLLATE "C" NOT NULL REFERENCES users (user_id),
        created_at_utc TEXT COLLATE "C" NOT NULL,
        expires_at_utc TEXT COLLATE "C" NOT NULL,
        -- Set on first use. Single-use is enforced by a guarded UPDATE on this
        -- column rather than by deleting the row, so a reused link is
        -- observable rather than merely absent.
        consumed_at_utc TEXT COLLATE "C"
    );

CREATE TABLE IF NOT EXISTS login_attempts (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        -- A hash of the email or the client address, never the value itself:
        -- this table exists to count failures, not to accumulate a record of
        -- who tried to log in from where.
        identifier_hash TEXT COLLATE "C" NOT NULL,
        scope TEXT COLLATE "C" NOT NULL,
        attempted_at_utc TEXT COLLATE "C" NOT NULL,
        successful INTEGER NOT NULL
    );

CREATE TABLE IF NOT EXISTS conversations (
        conversation_id TEXT COLLATE "C" PRIMARY KEY,
        user_id TEXT COLLATE "C" NOT NULL REFERENCES users (user_id),
        org_id TEXT COLLATE "C" REFERENCES organizations (org_id),
        created_at_utc TEXT COLLATE "C" NOT NULL,
        last_used_at_utc TEXT COLLATE "C" NOT NULL
    );

CREATE TABLE IF NOT EXISTS invitations (
        invitation_id TEXT COLLATE "C" PRIMARY KEY,
        org_id TEXT COLLATE "C" NOT NULL REFERENCES organizations (org_id),
        email TEXT COLLATE "C" NOT NULL,
        role TEXT COLLATE "C" NOT NULL,
        token_hash TEXT COLLATE "C" NOT NULL UNIQUE,
        invited_by TEXT COLLATE "C" NOT NULL REFERENCES users (user_id),
        created_at_utc TEXT COLLATE "C" NOT NULL,
        expires_at_utc TEXT COLLATE "C" NOT NULL,
        -- Set on redemption. Single-use is enforced by a guarded UPDATE on
        -- this column rather than by deleting the row, so a replayed link is
        -- observable rather than merely absent.
        accepted_at_utc TEXT COLLATE "C",
        accepted_by TEXT COLLATE "C" REFERENCES users (user_id),
        revoked_at_utc TEXT COLLATE "C",
        revoked_by TEXT COLLATE "C" REFERENCES users (user_id)
    );

CREATE TABLE IF NOT EXISTS audit_log (
        seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        event_id TEXT COLLATE "C" NOT NULL UNIQUE,
        occurred_at_utc TEXT COLLATE "C" NOT NULL,
        event_type TEXT COLLATE "C" NOT NULL,
        outcome TEXT COLLATE "C" NOT NULL,
        actor_user_id TEXT COLLATE "C",
        actor_role TEXT COLLATE "C",
        org_id TEXT COLLATE "C",
        target_type TEXT COLLATE "C",
        target_id TEXT COLLATE "C",
        request_id TEXT COLLATE "C",
        ip_hash TEXT COLLATE "C",
        detail_json TEXT COLLATE "C" NOT NULL,
        prev_hash TEXT COLLATE "C" NOT NULL,
        entry_hash TEXT COLLATE "C" NOT NULL
    );

CREATE TABLE IF NOT EXISTS email_verifications (
        verification_id TEXT COLLATE "C" PRIMARY KEY,
        token_hash TEXT COLLATE "C" NOT NULL UNIQUE,
        purpose TEXT COLLATE "C" NOT NULL,
        user_id TEXT COLLATE "C" REFERENCES users (user_id),
        email TEXT COLLATE "C",
        decoy INTEGER NOT NULL DEFAULT 0,
        provider TEXT COLLATE "C",
        provider_subject TEXT COLLATE "C",
        provider_display_name TEXT COLLATE "C",
        created_at_utc TEXT COLLATE "C" NOT NULL,
        expires_at_utc TEXT COLLATE "C" NOT NULL,
        -- Set once, under a guarded UPDATE: a verification completes once.
        completed_at_utc TEXT COLLATE "C"
    );

CREATE TABLE IF NOT EXISTS email_otps (
        otp_id TEXT COLLATE "C" PRIMARY KEY,
        verification_id TEXT COLLATE "C" NOT NULL REFERENCES email_verifications (verification_id),
        -- The destination, for the per-address sending cap. NULL on a decoy,
        -- so a decoy can never use up the real owner's allowance.
        email TEXT COLLATE "C",
        code_salt TEXT COLLATE "C" NOT NULL,
        code_hash TEXT COLLATE "C" NOT NULL,
        created_at_utc TEXT COLLATE "C" NOT NULL,
        expires_at_utc TEXT COLLATE "C" NOT NULL,
        attempts INTEGER NOT NULL DEFAULT 0,
        delivered INTEGER NOT NULL DEFAULT 0,
        consumed_at_utc TEXT COLLATE "C",
        -- Set when a newer code replaces this one: only the latest code works.
        superseded_at_utc TEXT COLLATE "C"
    );

CREATE TABLE IF NOT EXISTS user_identities (
        identity_id TEXT COLLATE "C" PRIMARY KEY,
        user_id TEXT COLLATE "C" NOT NULL REFERENCES users (user_id),
        provider TEXT COLLATE "C" NOT NULL,
        provider_subject TEXT COLLATE "C" NOT NULL,
        email_at_link TEXT COLLATE "C",
        created_at_utc TEXT COLLATE "C" NOT NULL,
        last_used_at_utc TEXT COLLATE "C",
        UNIQUE (provider, provider_subject)
    );

CREATE TABLE IF NOT EXISTS oauth_states (
        state_hash TEXT COLLATE "C" PRIMARY KEY,
        provider TEXT COLLATE "C" NOT NULL,
        code_verifier TEXT COLLATE "C" NOT NULL,
        created_at_utc TEXT COLLATE "C" NOT NULL,
        expires_at_utc TEXT COLLATE "C" NOT NULL,
        consumed_at_utc TEXT COLLATE "C"
    );

CREATE INDEX IF NOT EXISTS idx_email_verifications_user ON email_verifications (user_id);

CREATE INDEX IF NOT EXISTS idx_email_otps_verification ON email_otps (verification_id, created_at_utc);

CREATE INDEX IF NOT EXISTS idx_email_otps_email ON email_otps (email, created_at_utc);

CREATE INDEX IF NOT EXISTS idx_user_identities_user ON user_identities (user_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_organization_accounts_account ON organization_accounts (account_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_invitations_pending ON invitations (org_id, email) WHERE accepted_at_utc IS NULL AND revoked_at_utc IS NULL;

CREATE INDEX IF NOT EXISTS idx_invitations_org ON invitations (org_id);

CREATE INDEX IF NOT EXISTS idx_invitations_email ON invitations (email);

CREATE INDEX IF NOT EXISTS idx_memberships_user ON memberships (user_id);

CREATE INDEX IF NOT EXISTS idx_memberships_org ON memberships (org_id);

CREATE INDEX IF NOT EXISTS idx_org_accounts_account ON organization_accounts (account_id);

CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions (user_id);

CREATE INDEX IF NOT EXISTS idx_auth_tokens_user ON auth_tokens (user_id, purpose);

CREATE INDEX IF NOT EXISTS idx_login_attempts_lookup ON login_attempts (identifier_hash, attempted_at_utc);

CREATE INDEX IF NOT EXISTS idx_audit_actor ON audit_log (actor_user_id, occurred_at_utc);

CREATE INDEX IF NOT EXISTS idx_audit_org ON audit_log (org_id, occurred_at_utc);

CREATE INDEX IF NOT EXISTS idx_audit_type ON audit_log (event_type, occurred_at_utc);

-- Columns SQLite added after a table's first release (ADDED_COLUMNS).
ALTER TABLE agent_actions ADD COLUMN IF NOT EXISTS session_id TEXT COLLATE "C";
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at_utc TEXT COLLATE "C";
ALTER TABLE organizations ADD COLUMN IF NOT EXISTS updated_at_utc TEXT COLLATE "C";
ALTER TABLE users ADD COLUMN IF NOT EXISTS verification_sent_at_utc TEXT COLLATE "C";
ALTER TABLE users ADD COLUMN IF NOT EXISTS verification_resend_count INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS verification_cooldown_until_utc TEXT COLLATE "C";
