/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/actions/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pending Actions
         * @description Proposals awaiting confirmation, within the caller's account scope.
         */
        get: operations["pending_actions_api_actions_pending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/actions/{action_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Action Detail
         * @description The audit record for one action: state, timeline, and its effect.
         *
         *     Scoped like every other read — an action on another customer's account is
         *     reported as absent, not as forbidden, for the same reason the record
         *     layer does.
         */
        get: operations["action_detail_api_actions__action_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/actions/{action_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Action
         * @description Execute or reject one prepared action. The only path to a state change.
         *
         *     Every check the Phase 4 state machine offers is applied, under the
         *     *confirming* caller rather than the preparing one: the action must exist
         *     within this caller's account scope, belong to this conversation, still be
         *     pending, not have expired, still have a live target, and — when a
         *     fingerprint is supplied — still describe exactly what was reviewed. The
         *     status guard inside the UPDATE makes execution single-use even if two
         *     confirmations race.
         */
        post: operations["confirm_action_api_actions__action_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Audit
         * @description The security audit trail for the caller's own organisation.
         *
         *     Scoped to `caller.org_id`, which comes from the session — there is no
         *     parameter that widens it. The chain-verification result travels with the
         *     entries so a reader can tell whether what they are looking at is intact.
         */
        get: operations["audit_api_auth_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Verify a password and start a session.
         *
         *     On success a cookie is set and the body says whether a second factor is
         *     still outstanding. When it is, the session exists but is marked
         *     unsatisfied, and `authenticate` will admit it to `/mfa/challenge` and
         *     nowhere else.
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description End this session. Idempotent, and never an error.
         *
         *     A logout that fails leaves a user believing they signed out when they did
         *     not, so an unauthenticated call simply clears the cookie and reports
         *     success.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout All
         * @description Revoke every session this user holds, on every device.
         */
        post: operations["logout_all_api_auth_logout_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Who the caller is, and what their role permits.
         *
         *     The frontend renders from this. It is *not* an authorization decision:
         *     every permission listed is re-checked server-side at the point of use, and
         *     a client that lies to itself about this response gains nothing.
         */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/mfa/challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mfa Challenge
         * @description Complete the second factor on a half-authenticated session.
         */
        post: operations["mfa_challenge_api_auth_mfa_challenge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/mfa/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mfa Confirm */
        post: operations["mfa_confirm_api_auth_mfa_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/mfa/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mfa Disable */
        post: operations["mfa_disable_api_auth_mfa_disable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/mfa/enrol": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mfa Enrol
         * @description Generate a TOTP secret. MFA is not enabled until a code is confirmed.
         */
        post: operations["mfa_enrol_api_auth_mfa_enrol_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/organization/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Organization Members */
        get: operations["organization_members_api_auth_organization_members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/organization/members/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Member Role
         * @description Change a member's role within the caller's own organisation.
         *
         *     Note what is *not* taken from the request: the organisation. It comes from
         *     the caller's session, so there is no `org_id` field an attacker could point
         *     at somebody else's tenancy.
         */
        post: operations["set_member_role_api_auth_organization_members_role_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Password Change */
        post: operations["password_change_api_auth_password_change_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Password Reset
         * @description Redeem a reset link. Every session the user holds is revoked.
         */
        post: operations["password_reset_api_auth_password_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password/reset-request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Password Reset Request
         * @description Ask for a reset link. Always answers the same way.
         */
        post: operations["password_reset_request_api_auth_password_reset_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Create an account and issue an email-verification link.
         *
         *     The response is identical whether or not the address was already
         *     registered, so this endpoint cannot be used to test which addresses have
         *     accounts.
         */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/select-organization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Select Organization
         * @description Switch which organisation this session acts in.
         *
         *     Membership is re-checked here, and the choice is written to the *session
         *     row* rather than trusted per-request. A non-member gets a 404 — the same
         *     answer an organisation that does not exist gets, so this endpoint cannot be
         *     used to discover which organisation ids are real.
         */
        post: operations["select_organization_api_auth_select_organization_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description This user's sessions, so they can see a device they do not recognise.
         */
        get: operations["list_sessions_api_auth_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Email */
        post: operations["verify_email_api_auth_verify_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description Answer one natural-language request with its evidence.
         *
         *     The authorization context is built from the caller's identity before the
         *     message is read, and nothing in the message can widen it. Account ids in
         *     prose are treated as text; the agent's scope comes from records it was
         *     permitted to resolve.
         */
        post: operations["chat_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/principals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Principals
         * @description The mock identities this deployment accepts, and the scope each holds.
         *
         *     Exists so the demo is self-describing. It lists no credentials, because
         *     there are none: Phase 5's authentication is deliberately a mock, and a
         *     real identity provider replaces `auth/principals.py` without touching
         *     anything below it.
         */
        get: operations["principals_api_principals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness plus what is actually configured.
         *
         *     Answers 200 even when the database has not been built, reporting
         *     `status: "degraded"` — a health check that fails to respond tells an
         *     operator less than one that responds saying what is missing.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionConfirmationRequest
         * @description Confirm or reject one prepared action.
         *
         *     Confirmation is a distinct API call with a closed vocabulary. A user typing
         *     "okay" into the chat endpoint does not confirm anything: `/api/chat` has no
         *     path to execution at all, which is what makes the gate structural rather
         *     than a matter of parsing intent correctly.
         */
        ActionConfirmationRequest: {
            decision: components["schemas"]["ConfirmationDecision"];
            /** Expected Fingerprint */
            expected_fingerprint?: string | null;
            /** Request Id */
            request_id?: string | null;
            /** Session Id */
            session_id?: string | null;
            /** User Id */
            user_id?: string | null;
        };
        /** ActionConfirmationResponse */
        ActionConfirmationResponse: {
            action: components["schemas"]["ExecutedActionView"];
            action_status: components["schemas"]["ActionState"];
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
        };
        /** ActionDetailResponse */
        ActionDetailResponse: {
            action: components["schemas"]["ExecutedActionView"];
            action_status: components["schemas"]["ActionState"];
        };
        /**
         * ActionState
         * @description Action lifecycle as the API reports it.
         *
         *     Extends `ActionStatus` with `NONE`, so a response always states the action
         *     situation instead of leaving a client to infer it from a null field.
         *
         *     `CONFIRMED` is part of the contract but is not currently emitted: Phase 4's
         *     state machine confirms and executes inside one guarded transaction, so a
         *     successfully confirmed action is already `EXECUTED` by the time anyone can
         *     observe it. It is listed here so a future asynchronous executor does not
         *     need a breaking contract change.
         * @enum {string}
         */
        ActionState: "none" | "pending_confirmation" | "confirmed" | "executed" | "rejected" | "expired" | "failed";
        /**
         * ChatRequest
         * @description A natural-language request plus the identity it is made under.
         *
         *     `user_id` establishes the authorization context; it is looked up in the
         *     mock principal directory server-side. It is *not* trusted to describe its
         *     own permissions, and nothing in `message` can alter them —
         *     see `app/backend/auth/principals.py`.
         */
        ChatRequest: {
            /** Account Scope */
            account_scope?: string[] | null;
            /** Message */
            message: string;
            /** Request Id */
            request_id?: string | null;
            /** Session Id */
            session_id?: string | null;
            /** User Id */
            user_id?: string | null;
        };
        /**
         * ChatResponse
         * @description The full result of one natural-language request.
         */
        ChatResponse: {
            /** Account Scope */
            account_scope: string[];
            /** @default none */
            action_status: components["schemas"]["ActionState"];
            /** Answer */
            answer: string;
            /**
             * Escalation Recommended
             * @default false
             */
            escalation_recommended: boolean;
            outcome: components["schemas"]["ResponseOutcome"];
            /**
             * Policy Decisions
             * @default []
             */
            policy_decisions: components["schemas"]["PolicyDecisionView"][];
            proposed_action?: components["schemas"]["ProposedActionView"] | null;
            /** Reference Time */
            reference_time?: string | null;
            /** Request Id */
            request_id: string;
            /**
             * Responded At Utc
             * Format: date-time
             */
            responded_at_utc: string;
            role: components["schemas"]["Role"];
            /** Session Id */
            session_id: string;
            /**
             * Sources
             * @default []
             */
            sources: components["schemas"]["SourceRef"][];
            /**
             * Step Budget Exhausted
             * @default false
             */
            step_budget_exhausted: boolean;
            /**
             * Tools Used
             * @default []
             */
            tools_used: components["schemas"]["ToolUse"][];
            /**
             * Uncertainties
             * @default []
             */
            uncertainties: string[];
            /** User Id */
            user_id: string;
        };
        /**
         * ConfirmationDecision
         * @description Explicit, unambiguous. Free text is never interpreted as consent.
         * @enum {string}
         */
        ConfirmationDecision: "approve" | "reject";
        /**
         * ExecutedActionView
         * @description The audit record of an action that reached a terminal state.
         *
         *     Carries the timeline and the effect's identifier — enough to prove what
         *     happened and when — without exposing table names or row internals.
         */
        ExecutedActionView: {
            /** Account Id */
            account_id: string | null;
            /** Action Id */
            action_id: string;
            /** Action Type */
            action_type: string;
            /** Confirmed At Utc */
            confirmed_at_utc: string | null;
            /** Confirmed By */
            confirmed_by: string | null;
            /**
             * Evidence Chunk Ids
             * @default []
             */
            evidence_chunk_ids: string[];
            /** Executed At Utc */
            executed_at_utc: string | null;
            /** Failure Reason */
            failure_reason?: string | null;
            /** Parameters */
            parameters: {
                [key: string]: string;
            };
            /**
             * Prepared At Utc
             * Format: date-time
             */
            prepared_at_utc: string;
            /** Preview */
            preview: string;
            /** Rejected At Utc */
            rejected_at_utc: string | null;
            /** Requested By */
            requested_by: string;
            /** Requested By Role */
            requested_by_role: string;
            /** Result */
            result?: {
                [key: string]: string;
            } | null;
            status: components["schemas"]["ActionState"];
            /** Target Id */
            target_id: string;
            /** Target Type */
            target_type: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Liveness plus enough configuration to know what is running.
         *
         *     Reports the provider *mode*, never its credentials, and no filesystem
         *     paths: `/health` is often the most-exposed endpoint in a deployment.
         */
        HealthResponse: {
            /** App Env */
            app_env: string;
            /**
             * Auth Mode
             * @default session
             */
            auth_mode: string;
            /**
             * Checked At Utc
             * Format: date-time
             */
            checked_at_utc: string;
            /** Database Ready */
            database_ready: boolean;
            /** Dataset Snapshot */
            dataset_snapshot?: string | null;
            /** Documents Indexed */
            documents_indexed: number;
            /** Max Tool Steps */
            max_tool_steps: number;
            /** Model */
            model?: string | null;
            /** Provider Mode */
            provider_mode: string;
            /** State Changing Actions Enabled */
            state_changing_actions_enabled: boolean;
            /** Status */
            status: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MemberRoleRequest */
        MemberRoleRequest: {
            /** Role */
            role: string;
            /** User Id */
            user_id: string;
        };
        /** MfaCodeRequest */
        MfaCodeRequest: {
            /** Code */
            code: string;
        };
        /** MfaDisableRequest */
        MfaDisableRequest: {
            /** Code */
            code?: string | null;
            /** Password */
            password: string;
        };
        /** PasswordChangeRequest */
        PasswordChangeRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** PasswordResetCompleteRequest */
        PasswordResetCompleteRequest: {
            /** New Password */
            new_password: string;
            /** Token */
            token: string;
        };
        /** PasswordResetRequest */
        PasswordResetRequest: {
            /** Email */
            email: string;
        };
        /** PendingActionsResponse */
        PendingActionsResponse: {
            /**
             * Actions
             * @default []
             */
            actions: components["schemas"]["ProposedActionView"][];
            /** Count */
            count: number;
        };
        /**
         * PolicyDecisionView
         * @description A deterministic decision with the arithmetic that produced it.
         */
        PolicyDecisionView: {
            /** Account Id */
            account_id: string;
            /** Amount */
            amount?: string | null;
            /** Amount Label */
            amount_label?: string | null;
            /** Applies */
            applies?: boolean | null;
            /** Breached */
            breached?: boolean | null;
            /** Calculation */
            calculation?: string | null;
            /** Controlling Rule */
            controlling_rule: string;
            /**
             * Controlling Sources
             * @default []
             */
            controlling_sources: string[];
            /** Currency */
            currency?: string | null;
            /** Decision Type */
            decision_type: string;
            /** Elapsed Minutes */
            elapsed_minutes?: string | null;
            /**
             * Evidence Chunk Ids
             * @default []
             */
            evidence_chunk_ids: string[];
            /**
             * Inputs
             * @default {}
             */
            inputs: {
                [key: string]: string | null;
            };
            /** Order Id */
            order_id?: string | null;
            /** Outcome */
            outcome: string;
            /**
             * Overrides
             * @default []
             */
            overrides: string[];
            /**
             * Requires Immediate Escalation
             * @default false
             */
            requires_immediate_escalation: boolean;
            /**
             * Requires Verification
             * @default false
             */
            requires_verification: boolean;
            /** Severity */
            severity?: string | null;
            /** Target Text */
            target_text?: string | null;
            /** Ticket Id */
            ticket_id?: string | null;
            /**
             * Verification Reasons
             * @default []
             */
            verification_reasons: string[];
        };
        /**
         * PrincipalView
         * @description A demo identity the API will accept. No credentials involved.
         */
        PrincipalView: {
            /** Account Scope */
            account_scope: string[];
            /** Description */
            description: string;
            /** Display Name */
            display_name: string;
            role: components["schemas"]["Role"];
            /** User Id */
            user_id: string;
        };
        /** PrincipalsResponse */
        PrincipalsResponse: {
            /**
             * Principals
             * @default []
             */
            principals: components["schemas"]["PrincipalView"][];
        };
        /**
         * ProposedActionView
         * @description A prepared action awaiting a human. Nothing here has happened yet.
         */
        ProposedActionView: {
            /** Account Id */
            account_id: string | null;
            /** Action Id */
            action_id: string;
            /** Action Type */
            action_type: string;
            /**
             * Confirmation Required
             * @default true
             */
            confirmation_required: boolean;
            /**
             * Evidence Chunk Ids
             * @default []
             */
            evidence_chunk_ids: string[];
            /**
             * Expires At Utc
             * Format: date-time
             */
            expires_at_utc: string;
            /** Parameter Fingerprint */
            parameter_fingerprint: string;
            /** Parameters */
            parameters: {
                [key: string]: string;
            };
            /** Preview */
            preview: string;
            /** Reason */
            reason: string | null;
            status: components["schemas"]["ActionState"];
            /** Target Id */
            target_id: string;
            /** Target Type */
            target_type: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * ResponseOutcome
         * @enum {string}
         */
        ResponseOutcome: "answered" | "needs_confirmation" | "uncertain" | "refused" | "error";
        /**
         * Role
         * @description Who is asking, in the terms the authorization layer cares about.
         *
         *     Phase 4 shipped the three internal roles. Phase 5 adds `CUSTOMER` for the
         *     external context the API must be able to demonstrate — an account holder
         *     talking to the assistant about their own account. It is additive: a
         *     customer is scoped to their own account ids and, like `READ_ONLY`, may not
         *     change state, so no existing behaviour shifts.
         *
         *     **`SUPPORT_MANAGER` grants nothing `SUPPORT_AGENT` does not.** The only
         *     authorization distinction this enum currently drives is `may_change_state`
         *     below, which admits both. The role is modelled and carried through the
         *     system so that a manager-only capability has somewhere to attach, but no
         *     such capability exists yet: the SOP's "any individual credit above
         *     INR 1,000 requires manager approval" is computed and reported by
         *     `policies/service_credit.py` rather than enforced here, because neither
         *     state-changing action this system ships issues a credit. Enforcing it would
         *     mean gating an action that does not exist. See docs/product.md.
         * @enum {string}
         */
        Role: "support_agent" | "support_manager" | "read_only" | "customer";
        /** SelectOrgRequest */
        SelectOrgRequest: {
            /** Org Id */
            org_id: string;
        };
        /**
         * SourceRef
         * @description One citation: where a claim came from, and how much it is worth.
         */
        SourceRef: {
            /** Account Id */
            account_id: string | null;
            /** Authority Tier */
            authority_tier: number;
            /** Chunk Id */
            chunk_id: string;
            /** Citation */
            citation: string;
            /** Document Id */
            document_id: string;
            /** Document Title */
            document_title: string;
            /** Excerpt */
            excerpt: string;
            /** Is Authoritative */
            is_authoritative: boolean;
            /** Is Deprecated */
            is_deprecated: boolean;
            /** Page */
            page: number;
            /** Section */
            section: string | null;
            /** Source File */
            source_file: string;
            /** Topic */
            topic: string;
        };
        /** TokenRequest */
        TokenRequest: {
            /** Token */
            token: string;
        };
        /**
         * ToolUse
         * @description One tool call, as an auditor would want to see it summarised.
         *
         *     Arguments are omitted on purpose: they are part of the planning trace, and
         *     the contract promises what was consulted and how it finished, not how the
         *     agent phrased its query.
         */
        ToolUse: {
            /** Message */
            message?: string | null;
            /** Status */
            status: string;
            /** Step */
            step: number;
            /** Summary */
            summary?: string | null;
            /** Tool Name */
            tool_name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    pending_actions_api_actions_pending_get: {
        parameters: {
            query?: {
                user_id?: string | null;
            };
            header?: {
                "x-parcelpilot-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingActionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    action_detail_api_actions__action_id__get: {
        parameters: {
            query?: {
                user_id?: string | null;
            };
            header?: {
                "x-parcelpilot-user"?: string | null;
            };
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_action_api_actions__action_id__confirm_post: {
        parameters: {
            query?: never;
            header?: {
                "x-parcelpilot-user"?: string | null;
            };
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionConfirmationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionConfirmationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_api_auth_audit_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    logout_all_api_auth_logout_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    mfa_challenge_api_auth_mfa_challenge_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaCodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mfa_confirm_api_auth_mfa_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaCodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mfa_disable_api_auth_mfa_disable_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaDisableRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mfa_enrol_api_auth_mfa_enrol_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    organization_members_api_auth_organization_members_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    set_member_role_api_auth_organization_members_role_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberRoleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    password_change_api_auth_password_change_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    password_reset_api_auth_password_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetCompleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    password_reset_request_api_auth_password_reset_request_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    select_organization_api_auth_select_organization_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectOrgRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_auth_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    verify_email_api_auth_verify_email_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_chat_post: {
        parameters: {
            query?: never;
            header?: {
                "x-parcelpilot-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    principals_api_principals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrincipalsResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
