/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/actions/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pending Actions
         * @description Proposals awaiting confirmation, within the caller's account scope.
         */
        get: operations["pending_actions_api_actions_pending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/actions/{action_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Action Detail
         * @description The audit record for one action: state, timeline, and its effect.
         *
         *     Scoped like every other read — an action on another customer's account is
         *     reported as absent, not as forbidden, for the same reason the record
         *     layer does.
         */
        get: operations["action_detail_api_actions__action_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/actions/{action_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Action
         * @description Execute or reject one prepared action. The only path to a state change.
         *
         *     Every check the Phase 4 state machine offers is applied, under the
         *     *confirming* caller rather than the preparing one: the action must exist
         *     within this caller's account scope, belong to this conversation, still be
         *     pending, not have expired, still have a live target, and — when a
         *     fingerprint is supplied — still describe exactly what was reviewed. The
         *     status guard inside the UPDATE makes execution single-use even if two
         *     confirmations race.
         */
        post: operations["confirm_action_api_actions__action_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description Answer one natural-language request with its evidence.
         *
         *     The authorization context is built from the caller's identity before the
         *     message is read, and nothing in the message can widen it. Account ids in
         *     prose are treated as text; the agent's scope comes from records it was
         *     permitted to resolve.
         */
        post: operations["chat_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/principals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Principals
         * @description The mock identities this deployment accepts, and the scope each holds.
         *
         *     Exists so the demo is self-describing. It lists no credentials, because
         *     there are none: Phase 5's authentication is deliberately a mock, and a
         *     real identity provider replaces `auth/principals.py` without touching
         *     anything below it.
         */
        get: operations["principals_api_principals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness plus what is actually configured.
         *
         *     Answers 200 even when the database has not been built, reporting
         *     `status: "degraded"` — a health check that fails to respond tells an
         *     operator less than one that responds saying what is missing.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionConfirmationRequest
         * @description Confirm or reject one prepared action.
         *
         *     Confirmation is a distinct API call with a closed vocabulary. A user typing
         *     "okay" into the chat endpoint does not confirm anything: `/api/chat` has no
         *     path to execution at all, which is what makes the gate structural rather
         *     than a matter of parsing intent correctly.
         */
        ActionConfirmationRequest: {
            decision: components["schemas"]["ConfirmationDecision"];
            /** Expected Fingerprint */
            expected_fingerprint?: string | null;
            /** Request Id */
            request_id?: string | null;
            /** Session Id */
            session_id?: string | null;
            /** User Id */
            user_id?: string | null;
        };
        /** ActionConfirmationResponse */
        ActionConfirmationResponse: {
            action: components["schemas"]["ExecutedActionView"];
            action_status: components["schemas"]["ActionState"];
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
        };
        /** ActionDetailResponse */
        ActionDetailResponse: {
            action: components["schemas"]["ExecutedActionView"];
            action_status: components["schemas"]["ActionState"];
        };
        /**
         * ActionState
         * @description Action lifecycle as the API reports it.
         *
         *     Extends `ActionStatus` with `NONE`, so a response always states the action
         *     situation instead of leaving a client to infer it from a null field.
         *
         *     `CONFIRMED` is part of the contract but is not currently emitted: Phase 4's
         *     state machine confirms and executes inside one guarded transaction, so a
         *     successfully confirmed action is already `EXECUTED` by the time anyone can
         *     observe it. It is listed here so a future asynchronous executor does not
         *     need a breaking contract change.
         * @enum {string}
         */
        ActionState: "none" | "pending_confirmation" | "confirmed" | "executed" | "rejected" | "expired" | "failed";
        /**
         * ChatRequest
         * @description A natural-language request plus the identity it is made under.
         *
         *     `user_id` establishes the authorization context; it is looked up in the
         *     mock principal directory server-side. It is *not* trusted to describe its
         *     own permissions, and nothing in `message` can alter them —
         *     see `app/backend/auth/principals.py`.
         */
        ChatRequest: {
            /** Account Scope */
            account_scope?: string[] | null;
            /** Message */
            message: string;
            /** Request Id */
            request_id?: string | null;
            /** Session Id */
            session_id?: string | null;
            /** User Id */
            user_id?: string | null;
        };
        /**
         * ChatResponse
         * @description The full result of one natural-language request.
         */
        ChatResponse: {
            /** Account Scope */
            account_scope: string[];
            /** @default none */
            action_status: components["schemas"]["ActionState"];
            /** Answer */
            answer: string;
            /**
             * Escalation Recommended
             * @default false
             */
            escalation_recommended: boolean;
            outcome: components["schemas"]["ResponseOutcome"];
            /**
             * Policy Decisions
             * @default []
             */
            policy_decisions: components["schemas"]["PolicyDecisionView"][];
            proposed_action?: components["schemas"]["ProposedActionView"] | null;
            /** Reference Time */
            reference_time?: string | null;
            /** Request Id */
            request_id: string;
            /**
             * Responded At Utc
             * Format: date-time
             */
            responded_at_utc: string;
            role: components["schemas"]["Role"];
            /** Session Id */
            session_id: string;
            /**
             * Sources
             * @default []
             */
            sources: components["schemas"]["SourceRef"][];
            /**
             * Step Budget Exhausted
             * @default false
             */
            step_budget_exhausted: boolean;
            /**
             * Tools Used
             * @default []
             */
            tools_used: components["schemas"]["ToolUse"][];
            /**
             * Uncertainties
             * @default []
             */
            uncertainties: string[];
            /** User Id */
            user_id: string;
        };
        /**
         * ConfirmationDecision
         * @description Explicit, unambiguous. Free text is never interpreted as consent.
         * @enum {string}
         */
        ConfirmationDecision: "approve" | "reject";
        /**
         * ExecutedActionView
         * @description The audit record of an action that reached a terminal state.
         *
         *     Carries the timeline and the effect's identifier — enough to prove what
         *     happened and when — without exposing table names or row internals.
         */
        ExecutedActionView: {
            /** Account Id */
            account_id: string | null;
            /** Action Id */
            action_id: string;
            /** Action Type */
            action_type: string;
            /** Confirmed At Utc */
            confirmed_at_utc: string | null;
            /** Confirmed By */
            confirmed_by: string | null;
            /**
             * Evidence Chunk Ids
             * @default []
             */
            evidence_chunk_ids: string[];
            /** Executed At Utc */
            executed_at_utc: string | null;
            /** Failure Reason */
            failure_reason?: string | null;
            /** Parameters */
            parameters: {
                [key: string]: string;
            };
            /**
             * Prepared At Utc
             * Format: date-time
             */
            prepared_at_utc: string;
            /** Preview */
            preview: string;
            /** Rejected At Utc */
            rejected_at_utc: string | null;
            /** Requested By */
            requested_by: string;
            /** Requested By Role */
            requested_by_role: string;
            /** Result */
            result?: {
                [key: string]: string;
            } | null;
            status: components["schemas"]["ActionState"];
            /** Target Id */
            target_id: string;
            /** Target Type */
            target_type: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Liveness plus enough configuration to know what is running.
         *
         *     Reports the provider *mode*, never its credentials, and no filesystem
         *     paths: `/health` is often the most-exposed endpoint in a deployment.
         */
        HealthResponse: {
            /** App Env */
            app_env: string;
            /**
             * Checked At Utc
             * Format: date-time
             */
            checked_at_utc: string;
            /** Database Ready */
            database_ready: boolean;
            /** Dataset Snapshot */
            dataset_snapshot?: string | null;
            /** Documents Indexed */
            documents_indexed: number;
            /** Max Tool Steps */
            max_tool_steps: number;
            /** Model */
            model?: string | null;
            /** Provider Mode */
            provider_mode: string;
            /** State Changing Actions Enabled */
            state_changing_actions_enabled: boolean;
            /** Status */
            status: string;
        };
        /** PendingActionsResponse */
        PendingActionsResponse: {
            /**
             * Actions
             * @default []
             */
            actions: components["schemas"]["ProposedActionView"][];
            /** Count */
            count: number;
        };
        /**
         * PolicyDecisionView
         * @description A deterministic decision with the arithmetic that produced it.
         */
        PolicyDecisionView: {
            /** Account Id */
            account_id: string;
            /** Amount */
            amount?: string | null;
            /** Amount Label */
            amount_label?: string | null;
            /** Applies */
            applies?: boolean | null;
            /** Calculation */
            calculation?: string | null;
            /** Controlling Rule */
            controlling_rule: string;
            /**
             * Controlling Sources
             * @default []
             */
            controlling_sources: string[];
            /** Currency */
            currency: string;
            /** Decision Type */
            decision_type: string;
            /**
             * Evidence Chunk Ids
             * @default []
             */
            evidence_chunk_ids: string[];
            /**
             * Inputs
             * @default {}
             */
            inputs: {
                [key: string]: string | null;
            };
            /** Order Id */
            order_id: string;
            /** Outcome */
            outcome: string;
            /**
             * Overrides
             * @default []
             */
            overrides: string[];
            /**
             * Requires Verification
             * @default false
             */
            requires_verification: boolean;
            /**
             * Verification Reasons
             * @default []
             */
            verification_reasons: string[];
        };
        /**
         * PrincipalView
         * @description A demo identity the API will accept. No credentials involved.
         */
        PrincipalView: {
            /** Account Scope */
            account_scope: string[];
            /** Description */
            description: string;
            /** Display Name */
            display_name: string;
            role: components["schemas"]["Role"];
            /** User Id */
            user_id: string;
        };
        /** PrincipalsResponse */
        PrincipalsResponse: {
            /**
             * Principals
             * @default []
             */
            principals: components["schemas"]["PrincipalView"][];
        };
        /**
         * ProposedActionView
         * @description A prepared action awaiting a human. Nothing here has happened yet.
         */
        ProposedActionView: {
            /** Account Id */
            account_id: string | null;
            /** Action Id */
            action_id: string;
            /** Action Type */
            action_type: string;
            /**
             * Confirmation Required
             * @default true
             */
            confirmation_required: boolean;
            /**
             * Evidence Chunk Ids
             * @default []
             */
            evidence_chunk_ids: string[];
            /**
             * Expires At Utc
             * Format: date-time
             */
            expires_at_utc: string;
            /** Parameter Fingerprint */
            parameter_fingerprint: string;
            /** Parameters */
            parameters: {
                [key: string]: string;
            };
            /** Preview */
            preview: string;
            /** Reason */
            reason: string | null;
            status: components["schemas"]["ActionState"];
            /** Target Id */
            target_id: string;
            /** Target Type */
            target_type: string;
        };
        /**
         * ResponseOutcome
         * @enum {string}
         */
        ResponseOutcome: "answered" | "needs_confirmation" | "uncertain" | "refused" | "error";
        /**
         * Role
         * @description Who is asking, in the terms the authorization layer cares about.
         *
         *     Phase 4 shipped the three internal roles. Phase 5 adds `CUSTOMER` for the
         *     external context the API must be able to demonstrate — an account holder
         *     talking to the assistant about their own account. It is additive: a
         *     customer is scoped to their own account ids and, like `READ_ONLY`, may not
         *     change state, so no existing behaviour shifts.
         * @enum {string}
         */
        Role: "support_agent" | "support_manager" | "read_only" | "customer";
        /**
         * SourceRef
         * @description One citation: where a claim came from, and how much it is worth.
         */
        SourceRef: {
            /** Account Id */
            account_id: string | null;
            /** Authority Tier */
            authority_tier: number;
            /** Chunk Id */
            chunk_id: string;
            /** Citation */
            citation: string;
            /** Document Id */
            document_id: string;
            /** Document Title */
            document_title: string;
            /** Excerpt */
            excerpt: string;
            /** Is Authoritative */
            is_authoritative: boolean;
            /** Is Deprecated */
            is_deprecated: boolean;
            /** Page */
            page: number;
            /** Section */
            section: string | null;
            /** Source File */
            source_file: string;
            /** Topic */
            topic: string;
        };
        /**
         * ToolUse
         * @description One tool call, as an auditor would want to see it summarised.
         *
         *     Arguments are omitted on purpose: they are part of the planning trace, and
         *     the contract promises what was consulted and how it finished, not how the
         *     agent phrased its query.
         */
        ToolUse: {
            /** Message */
            message?: string | null;
            /** Status */
            status: string;
            /** Step */
            step: number;
            /** Summary */
            summary?: string | null;
            /** Tool Name */
            tool_name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    pending_actions_api_actions_pending_get: {
        parameters: {
            query?: {
                user_id?: string | null;
            };
            header?: {
                "x-parcelpilot-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingActionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    action_detail_api_actions__action_id__get: {
        parameters: {
            query?: {
                user_id?: string | null;
            };
            header?: {
                "x-parcelpilot-user"?: string | null;
            };
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_action_api_actions__action_id__confirm_post: {
        parameters: {
            query?: never;
            header?: {
                "x-parcelpilot-user"?: string | null;
            };
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionConfirmationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionConfirmationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_chat_post: {
        parameters: {
            query?: never;
            header?: {
                "x-parcelpilot-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    principals_api_principals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrincipalsResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
